import type { EntityCacheTtlConfig } from '../cacheTtl.js';

export type CacheBackend = 'memory' | 'redis';
export type NotificationsPersistenceBackend = 'memory' | 'postgres';
export type AppEnv = 'development' | 'test' | 'staging' | 'production';
export type NodeRole = 'api' | 'worker';
export type AttestationEnforcementMode = 'strict' | 'report_only';

export type BffEnv = {
  appEnv: AppEnv;
  nodeRole: NodeRole;
  port: number;
  host: string;
  apiFootballBaseUrl: string;
  apiFootballKey: string;
  apiTimeoutMs: number;
  apiMaxRetries: number;
  rateLimitMax: number;
  rateLimitWindowMs: number;
  trustProxyHops: number;
  corsAllowedOrigins: string[];
  webAppOrigin: string | null;
  cacheMaxEntries: number;
  cacheCleanupIntervalMs: number;
  cacheTtlJitterPct: number;
  cacheLockTtlMs: number;
  cacheCoalesceWaitMs: number;
  upstreamGlobalRpmLimit: number;
  upstreamCircuitBreakerWindowMs: number;
  cacheBackend: CacheBackend;
  cacheStrictMode: boolean;
  redisUrl: string | null;
  redisCachePrefix: string;
  cacheTtl: EntityCacheTtlConfig;
  bffExposeErrorDetails: boolean;
  mobileSessionJwtSecret: string | null;
  mobileSessionTokenTtlMs: number;
  mobileRefreshTokenTtlMs: number;
  mobileAuthChallengeTtlMs: number;
  mobileAttestationAcceptMock: boolean;
  mobileAttestationEnforcementMode: AttestationEnforcementMode;
  mobileAuthEnforcedHosts: string[];
  mobilePlayIntegrityPackageName: string | null;
  mobilePlayIntegrityServiceAccountEmail: string | null;
  mobilePlayIntegrityServiceAccountPrivateKey: string | null;
  mobileAppAttestBundleId: string | null;
  mobileAppAttestTeamId: string | null;
  mobileAppAttestVerificationUrl: string | null;
  mobileAppAttestVerificationSecret: string | null;
  paginationCursorSecret: string;
  paginationCursorTtlMs: number;
  notificationsBackendEnabled: boolean;
  notificationsEventIngestEnabled: boolean;
  notificationsPersistenceBackend: NotificationsPersistenceBackend;
  notificationsFanoutMaxPerEvent: number;
  notificationsDeferredPromotionBatch: number;
  notificationsDeferredDelayMs: number;
  bffEnablePlayerCanonicalCacheKeys: boolean;
  bffEnablePlayerMatchesSwr: boolean;
  bffEnablePlayerOverviewRoute: boolean;
  databaseUrl: string | null;
  notificationsIngestToken: string | null;
  pushTokenEncryptionKey: string | null;
  firebaseProjectId: string | null;
  firebaseClientEmail: string | null;
  firebasePrivateKey: string | null;
  opsMetricsToken: string | null;
};
