import { StyleSheet } from 'react-native';

import type { ThemeColors } from '@ui/shared/theme/theme';

export function createMatchDetailsTabStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
    },
    content: {
      paddingHorizontal: 14,
      paddingTop: 12,
      paddingBottom: 26,
      gap: 12,
    },
    card: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      paddingHorizontal: 12,
      paddingVertical: 12,
      gap: 10,
    },
    cardTitle: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '800',
    },
    cardSubtitle: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
    },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    splitCol: {
      flex: 1,
      gap: 6,
    },
    metricLabel: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
    },
    metricValue: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '800',
    },
    badge: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.primary,
      backgroundColor: `${colors.primary}1C`,
      paddingHorizontal: 9,
      paddingVertical: 3,
      alignSelf: 'flex-start',
    },
    badgeText: {
      color: colors.primary,
      fontSize: 11,
      fontWeight: '700',
      textTransform: 'uppercase',
    },
    chipRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 8,
    },
    chip: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.chipBorder,
      backgroundColor: colors.chipBackground,
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    chipActive: {
      borderColor: colors.primary,
      backgroundColor: `${colors.primary}1F`,
    },
    chipText: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '700',
    },
    chipTextActive: {
      color: colors.primary,
    },
    probBarWrap: {
      gap: 6,
    },
    probBarRail: {
      height: 8,
      borderRadius: 999,
      backgroundColor: colors.surfaceElevated,
      overflow: 'hidden',
    },
    probBarFill: {
      height: '100%',
      borderRadius: 999,
      backgroundColor: colors.primary,
    },
    eventRow: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceElevated,
      paddingHorizontal: 10,
      paddingVertical: 8,
      gap: 2,
    },
    eventRowNew: {
      borderColor: colors.primary,
      backgroundColor: `${colors.primary}16`,
    },
    eventMinute: {
      color: colors.primary,
      fontSize: 12,
      fontWeight: '800',
    },
    eventLabel: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '700',
    },
    eventDetail: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
    },
    statRow: {
      gap: 6,
    },
    statHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    statLabel: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '700',
      flex: 1,
      textAlign: 'center',
    },
    statValue: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '800',
      minWidth: 44,
      textAlign: 'center',
    },
    statBarRail: {
      flexDirection: 'row',
      height: 10,
      borderRadius: 999,
      backgroundColor: colors.surfaceElevated,
      overflow: 'hidden',
    },
    statBarHome: {
      backgroundColor: colors.primary,
      height: '100%',
    },
    statBarAway: {
      backgroundColor: `${colors.textMuted}A3`,
      height: '100%',
    },
    pitchCard: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: '#163423',
      padding: 10,
      gap: 8,
    },
    pitchRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 6,
    },
    playerChip: {
      minHeight: 30,
      flex: 1,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.18)',
      backgroundColor: 'rgba(0,0,0,0.28)',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    playerChipText: {
      color: '#F3FFF8',
      fontSize: 11,
      fontWeight: '700',
      textAlign: 'center',
    },
    rosterRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
      paddingVertical: 5,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    rosterName: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '700',
      flex: 1,
    },
    rosterMeta: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '600',
    },
    splitDivider: {
      width: 1,
      alignSelf: 'stretch',
      backgroundColor: colors.border,
    },
    standingsTabContainer: {
      flex: 1,
      paddingTop: 12,
    },
    emptyText: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '600',
      textAlign: 'center',
    },
    livePulse: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.primary,
      marginRight: 8,
    },
    inlineRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    newsCard: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceElevated,
      paddingHorizontal: 10,
      paddingVertical: 8,
      gap: 6,
    },
    newsTitle: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '700',
    },
    newsText: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
      lineHeight: 16,
    },
    teamHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    teamLogo: {
      width: 22,
      height: 22,
    },
    lineupTeamBlock: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      overflow: 'hidden',
    },
    lineupTeamHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.surfaceElevated,
    },
    lineupTeamLogo: {
      width: 18,
      height: 18,
    },
    lineupTeamName: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '800',
      flexShrink: 1,
    },
    lineupTeamFormation: {
      color: colors.textMuted,
      fontSize: 17,
      fontWeight: '700',
      marginLeft: 'auto',
    },
    lineupPitchSurface: {
      backgroundColor: '#17191F',
      paddingHorizontal: 10,
      paddingTop: 14,
      paddingBottom: 18,
      gap: 22,
      position: 'relative',
    },
    lineupPitchCenterLine: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: '50%',
      height: 1.5,
      backgroundColor: 'rgba(255,255,255,0.08)',
    },
    lineupPitchCenterCircle: {
      position: 'absolute',
      top: '50%',
      left: '50%',
      width: 84,
      height: 84,
      borderRadius: 42,
      marginLeft: -42,
      marginTop: -42,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.08)',
    },
    lineupPitchPenaltyTop: {
      position: 'absolute',
      top: 0,
      left: '24%',
      right: '24%',
      height: '16%',
      borderWidth: 1.5,
      borderTopWidth: 0,
      borderColor: 'rgba(255,255,255,0.08)',
    },
    lineupPitchPenaltyBottom: {
      position: 'absolute',
      bottom: 0,
      left: '24%',
      right: '24%',
      height: '16%',
      borderWidth: 1.5,
      borderBottomWidth: 0,
      borderColor: 'rgba(255,255,255,0.08)',
    },
    lineupPitchRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-around',
      gap: 8,
    },
    lineupPlayerNode: {
      alignItems: 'center',
      width: 86,
      gap: 4,
    },
    lineupPlayerAvatarWrap: {
      width: 66,
      height: 66,
      borderRadius: 33,
      borderWidth: 3,
      borderColor: 'rgba(255,255,255,0.14)',
      backgroundColor: '#2B2D34',
      overflow: 'hidden',
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
    },
    lineupPlayerAvatar: {
      width: '100%',
      height: '100%',
    },
    lineupPlayerAvatarFallback: {
      width: '100%',
      height: '100%',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#2B2D34',
    },
    lineupPlayerAvatarFallbackText: {
      color: '#E5E7EB',
      fontSize: 18,
      fontWeight: '900',
    },
    lineupRatingChip: {
      position: 'absolute',
      right: -4,
      top: -6,
      borderRadius: 999,
      minWidth: 44,
      paddingHorizontal: 8,
      paddingVertical: 2,
      alignItems: 'center',
    },
    lineupRatingChipGood: {
      backgroundColor: '#34D399',
    },
    lineupRatingChipWarning: {
      backgroundColor: '#FB923C',
    },
    lineupRatingChipElite: {
      backgroundColor: '#38BDF8',
    },
    lineupRatingChipNeutral: {
      backgroundColor: '#A3A3A3',
    },
    lineupRatingChipText: {
      color: '#111827',
      fontSize: 12,
      fontWeight: '900',
    },
    lineupPlayerEventWrap: {
      position: 'absolute',
      left: -10,
      top: -8,
      alignItems: 'center',
      gap: 1,
    },
    lineupPlayerEventMinute: {
      color: '#E5E7EB',
      fontSize: 11,
      fontWeight: '800',
    },
    lineupBenchEventWrap: {
      position: 'absolute',
      left: -12,
      top: -6,
      alignItems: 'center',
      gap: 1,
    },
    lineupBenchEventMinute: {
      color: '#34D399',
      fontSize: 11,
      fontWeight: '800',
    },
    lineupPlayerGoalIconWrap: {
      position: 'absolute',
      right: -2,
      bottom: -2,
      width: 19,
      height: 19,
      borderRadius: 999,
      backgroundColor: '#E5E7EB',
      alignItems: 'center',
      justifyContent: 'center',
    },
    lineupPlayerCardIconWrap: {
      position: 'absolute',
      left: -2,
      bottom: -2,
      width: 19,
      height: 19,
      borderRadius: 999,
      backgroundColor: '#E5E7EB',
      alignItems: 'center',
      justifyContent: 'center',
    },
    lineupPlayerName: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '700',
      textAlign: 'center',
    },
    lineupTwoColumnsWrap: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
    },
    lineupColumn: {
      flex: 1,
      gap: 8,
    },
    lineupColumnHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    lineupColumnTeamLogo: {
      width: 16,
      height: 16,
    },
    lineupColumnTeamName: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '700',
      flex: 1,
    },
    lineupColumnList: {
      gap: 10,
    },
    lineupCoachCard: {
      alignItems: 'center',
      gap: 8,
      paddingVertical: 4,
    },
    lineupCoachAvatarWrap: {
      width: 78,
      height: 78,
      borderRadius: 39,
      borderWidth: 3,
      borderColor: 'rgba(255,255,255,0.14)',
      overflow: 'hidden',
      backgroundColor: '#2B2D34',
      alignItems: 'center',
      justifyContent: 'center',
    },
    lineupCoachAvatar: {
      width: '100%',
      height: '100%',
    },
    lineupCoachAvatarFallback: {
      width: '100%',
      height: '100%',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#2B2D34',
    },
    lineupCoachName: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '700',
      textAlign: 'center',
    },
    lineupBenchItem: {
      alignItems: 'center',
      gap: 4,
      paddingBottom: 2,
    },
    lineupBenchPosition: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
      textAlign: 'center',
    },
    lineupAbsenceItem: {
      alignItems: 'center',
      gap: 4,
      paddingBottom: 2,
    },
    lineupAbsenceAvatarWrap: {
      width: 72,
      height: 72,
      borderRadius: 36,
      borderWidth: 3,
      borderColor: 'rgba(255,255,255,0.14)',
      overflow: 'hidden',
      backgroundColor: '#2B2D34',
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
    },
    lineupAbsenceAvatar: {
      width: '100%',
      height: '100%',
    },
    lineupAbsenceAvatarFallback: {
      width: '100%',
      height: '100%',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#2B2D34',
    },
    lineupAbsenceBadge: {
      position: 'absolute',
      right: -2,
      bottom: -2,
      width: 20,
      height: 20,
      borderRadius: 999,
      borderWidth: 2,
      borderColor: '#1E293B',
      alignItems: 'center',
      justifyContent: 'center',
    },
    lineupAbsenceBadgeInjured: {
      backgroundColor: '#F8FAFC',
    },
    lineupAbsenceBadgeSuspended: {
      backgroundColor: '#EF4444',
    },
    lineupAbsenceName: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '700',
      textAlign: 'center',
    },
    lineupAbsenceReason: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
      textAlign: 'center',
    },
    lineupAbsenceStatus: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
      textAlign: 'center',
    },
    lineupLegendGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      rowGap: 12,
      columnGap: 8,
    },
    lineupLegendItem: {
      width: '48%',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    lineupLegendText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '600',
      flex: 1,
    },
  });
}

export type MatchDetailsTabStyles = ReturnType<typeof createMatchDetailsTabStyles>;
