import { StyleSheet } from 'react-native';

import type { ThemeColors } from '@ui/shared/theme/theme';

export function createMatchDetailsTabStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
    },
    content: {
      paddingHorizontal: 14,
      paddingTop: 12,
      paddingBottom: 26,
      gap: 12,
    },
    card: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      paddingHorizontal: 16,
      paddingVertical: 18,
      gap: 16,
    },
    cardTitle: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '800',
    },
    cardSubtitle: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
    },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    splitCol: {
      flex: 1,
      gap: 12,
    },
    metricLabel: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
    },
    metricValue: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '800',
    },
    badge: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.primary,
      backgroundColor: `${colors.primary}1C`,
      paddingHorizontal: 9,
      paddingVertical: 3,
      alignSelf: 'flex-start',
    },
    badgeText: {
      color: colors.primary,
      fontSize: 11,
      fontWeight: '700',
      textTransform: 'uppercase',
    },
    chipRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 8,
    },
    chip: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: 'transparent',
      paddingHorizontal: 14,
      paddingVertical: 8,
    },
    chipActive: {
      borderColor: colors.primary,
      backgroundColor: `${colors.primary}1A`,
    },
    chipText: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '600',
    },
    chipTextActive: {
      color: colors.primary,
      fontWeight: '800',
    },
    probBarWrap: {
      gap: 6,
    },
    probBarRail: {
      height: 8,
      borderRadius: 999,
      backgroundColor: colors.surfaceElevated,
      overflow: 'hidden',
    },
    probBarFill: {
      height: '100%',
      borderRadius: 999,
      backgroundColor: colors.primary,
    },
    timelineContainer: {
      position: 'relative',
      paddingVertical: 16,
    },
    timelineCenterLine: {
      position: 'absolute',
      top: 16,
      bottom: 16,
      left: '50%',
      width: 2,
      backgroundColor: colors.border,
      marginLeft: -1,
    },
    timelineRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 20,
      position: 'relative',
      width: '100%',
    },
    timelineMinuteBadge: {
      minWidth: 32,
      height: 32,
      paddingHorizontal: 6,
      borderRadius: 16,
      backgroundColor: colors.surfaceElevated,
      borderWidth: 2,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      marginHorizontal: 8,
    },
    timelineMinuteText: {
      color: colors.text,
      fontSize: 11,
      fontWeight: '800',
    },
    timelineContentEmpty: {
      flex: 1,
    },
    timelineContentLeft: {
      flex: 1,
      alignItems: 'flex-end',
      paddingRight: 12,
    },
    timelineContentRight: {
      flex: 1,
      alignItems: 'flex-start',
      paddingLeft: 12,
    },
    timelineCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surfaceElevated,
      borderRadius: 12,
      padding: 8,
      gap: 8,
      maxWidth: '100%',
      flexShrink: 1,
    },
    timelineCardLeft: {
      flexDirection: 'row-reverse',
    },
    timelineAvatarWrap: {
      width: 36,
      height: 36,
      borderRadius: 18,
      overflow: 'hidden',
      backgroundColor: '#F3F4F6',
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    timelineAvatar: {
      width: '100%',
      height: '100%',
    },
    timelineAvatarFallbackText: {
      color: '#4B5563',
      fontSize: 12,
      fontWeight: '900',
    },
    timelineEventDetailsLeft: {
      alignItems: 'flex-end',
      flexShrink: 1,
    },
    timelineEventDetailsRight: {
      alignItems: 'flex-start',
      flexShrink: 1,
    },
    timelinePlayerName: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '700',
      marginBottom: 2,
      flexShrink: 1,
    },
    timelineEventSubLine: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      flexShrink: 1,
    },
    timelineEventSubLineReversed: {
      flexDirection: 'row-reverse',
    },
    timelineEventText: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
      flexShrink: 1,
    },
    timelineIconWrap: {
      alignItems: 'center',
      justifyContent: 'center',
      width: 16,
      height: 16,
    },
    eventRow: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceElevated,
      paddingHorizontal: 10,
      paddingVertical: 8,
      gap: 2,
    },
    eventRowNew: {
      borderColor: colors.primary,
      backgroundColor: `${colors.primary}16`,
    },
    eventMinute: {
      color: colors.primary,
      fontSize: 12,
      fontWeight: '800',
    },
    eventLabel: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '700',
    },
    eventDetail: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
    },
    statRow: {
      gap: 8,
    },
    statHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    statLabel: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '600',
      flex: 1,
      textAlign: 'center',
    },
    statValue: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '900',
      minWidth: 44,
      textAlign: 'center',
    },
    statBarRail: {
      flexDirection: 'row',
      height: 6,
      borderRadius: 999,
      backgroundColor: 'rgba(255,255,255,0.06)',
      overflow: 'hidden',
    },
    statBarHome: {
      backgroundColor: colors.primary,
      height: '100%',
      borderTopRightRadius: 2,
      borderBottomRightRadius: 2,
    },
    statBarAway: {
      backgroundColor: colors.textMuted,
      height: '100%',
      borderTopLeftRadius: 2,
      borderBottomLeftRadius: 2,
    },
    pitchCard: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: '#163423',
      padding: 10,
      gap: 8,
    },
    pitchRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 6,
    },
    playerChip: {
      minHeight: 30,
      flex: 1,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.18)',
      backgroundColor: 'rgba(0,0,0,0.28)',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    playerChipText: {
      color: '#F3FFF8',
      fontSize: 11,
      fontWeight: '700',
      textAlign: 'center',
    },
    rosterRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
      paddingVertical: 5,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    rosterName: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '700',
      flex: 1,
    },
    rosterMeta: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '600',
    },
    splitDivider: {
      width: 1,
      alignSelf: 'stretch',
      backgroundColor: colors.border,
    },
    standingsTabContainer: {
      flex: 1,
      paddingTop: 12,
    },
    emptyText: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '600',
      textAlign: 'center',
    },
    livePulse: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.primary,
      marginRight: 8,
    },
    inlineRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    preMatchInlineInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    preMatchMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    preMatchRecentColumns: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
    },
    preMatchRecentColumn: {
      flex: 1,
      gap: 10,
    },
    preMatchRecentTeamHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    preMatchRecentTeamTitle: {
      flex: 1,
      color: colors.text,
      fontSize: 13,
      fontWeight: '800',
    },
    preMatchRecentMatchRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    preMatchTeamLogo: {
      width: 20,
      height: 20,
    },
    preMatchTeamLogoFallback: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: colors.surfaceElevated,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    preMatchTeamLogoFallbackText: {
      color: colors.textMuted,
      fontSize: 8,
      fontWeight: '800',
    },
    preMatchResultBadge: {
      minWidth: 58,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 6,
      paddingHorizontal: 8,
    },
    preMatchResultBadgeWin: {
      backgroundColor: '#16A34A',
    },
    preMatchResultBadgeDraw: {
      backgroundColor: '#6B7280',
    },
    preMatchResultBadgeLoss: {
      backgroundColor: '#DC2626',
    },
    preMatchResultBadgeText: {
      color: '#FFFFFF',
      fontSize: 13,
      fontWeight: '800',
    },
    preMatchStandingsHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      paddingBottom: 8,
      paddingHorizontal: 2,
    },
    preMatchStandingsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      paddingHorizontal: 2,
    },
    preMatchStandingsCell: {
      width: 24,
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '700',
      textAlign: 'center',
      textTransform: 'uppercase',
    },
    preMatchStandingsCellRank: {
      width: 28,
      textAlign: 'left',
    },
    preMatchStandingsCellTeam: {
      flex: 1,
      minWidth: 80,
      textAlign: 'left',
    },
    preMatchStandingsCellPoints: {
      width: 34,
      textAlign: 'right',
    },
    preMatchStandingsCellValue: {
      width: 24,
      color: colors.text,
      fontSize: 12,
      fontWeight: '700',
      textAlign: 'center',
    },
    preMatchStandingsTeamCell: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      minWidth: 80,
    },
    preMatchStandingsTeamName: {
      flex: 1,
      color: colors.text,
      fontSize: 12,
      fontWeight: '700',
    },
    preMatchLeadersRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      paddingTop: 10,
    },
    preMatchLeaderSide: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    preMatchLeadersCenter: {
      width: 88,
      alignItems: 'center',
    },
    preMatchLeaderAvatar: {
      width: 36,
      height: 36,
      borderRadius: 18,
    },
    preMatchLeaderAvatarFallback: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.surfaceElevated,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    preMatchLeaderAvatarFallbackText: {
      color: colors.textMuted,
      fontSize: 10,
      fontWeight: '800',
    },
    preMatchLeaderTextWrap: {
      flex: 1,
      alignItems: 'flex-start',
    },
    preMatchLeaderTextWrapRight: {
      flex: 1,
      alignItems: 'flex-end',
    },
    preMatchLeaderName: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '700',
    },
    preMatchLeaderNameRight: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '700',
      textAlign: 'right',
    },
    preMatchLeaderValue: {
      color: colors.primary,
      fontSize: 16,
      fontWeight: '900',
    },
    preMatchLeaderValueRight: {
      color: colors.primary,
      fontSize: 16,
      fontWeight: '900',
      textAlign: 'right',
    },
    newsCard: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceElevated,
      paddingHorizontal: 12,
      paddingVertical: 12,
      gap: 8,
    },
    newsTitle: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '700',
    },
    newsText: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
      lineHeight: 16,
    },
    teamHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    teamLogo: {
      width: 22,
      height: 22,
    },
    lineupTeamBlock: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      overflow: 'hidden',
    },
    lineupTeamHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.surfaceElevated,
    },
    lineupTeamHeaderAway: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      gap: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      backgroundColor: colors.surfaceElevated,
    },
    lineupTeamLogo: {
      width: 18,
      height: 18,
    },
    lineupTeamName: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '800',
      flexShrink: 1,
    },
    lineupTeamFormation: {
      color: colors.textMuted,
      fontSize: 17,
      fontWeight: '700',
      marginLeft: 'auto',
    },
    lineupTeamFormationAway: {
      marginLeft: 0,
      marginRight: 'auto',
    },
    lineupPitchSurface: {
      backgroundColor: '#1E293B',
      position: 'relative',
      height: 980,
    },
    lineupPitchHalfHome: {
      flex: 1,
      paddingHorizontal: 10,
      paddingTop: 16,
      paddingBottom: 16,
      justifyContent: 'space-around',
    },
    lineupPitchHalfAway: {
      flex: 1,
      paddingHorizontal: 10,
      paddingTop: 16,
      paddingBottom: 16,
      flexDirection: 'column-reverse',
      justifyContent: 'space-around',
    },
    lineupPitchCenterLine: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: '50%',
      height: 1.5,
      backgroundColor: 'rgba(255,255,255,0.08)',
    },
    lineupPitchCenterCircle: {
      position: 'absolute',
      top: '50%',
      left: '50%',
      width: 84,
      height: 84,
      borderRadius: 42,
      marginLeft: -42,
      marginTop: -42,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.08)',
    },
    lineupPitchPenaltyTop: {
      position: 'absolute',
      top: 0,
      left: '24%',
      right: '24%',
      height: '16%',
      borderWidth: 1.5,
      borderTopWidth: 0,
      borderColor: 'rgba(255,255,255,0.08)',
    },
    lineupPitchPenaltyBottom: {
      position: 'absolute',
      bottom: 0,
      left: '24%',
      right: '24%',
      height: '16%',
      borderWidth: 1.5,
      borderBottomWidth: 0,
      borderColor: 'rgba(255,255,255,0.08)',
    },
    lineupPitchRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-around',
      gap: 2,
      zIndex: 2,
    },
    lineupPlayerNode: {
      alignItems: 'center',
      width: 70,
      gap: 4,
      zIndex: 5,
    },
    lineupPlayerAvatarWrap: {
      width: 54,
      height: 54,
      position: 'relative',
      zIndex: 1,
    },
    lineupPlayerImageWrap: {
      width: '100%',
      height: '100%',
      borderRadius: 27,
      borderWidth: 2,
      borderColor: 'rgba(255,255,255,0.4)',
      backgroundColor: '#F3F4F6',
      overflow: 'hidden',
      alignItems: 'center',
      justifyContent: 'center',
    },
    lineupPlayerAvatar: {
      width: '100%',
      height: '100%',
    },
    lineupPlayerAvatarFallback: {
      width: '100%',
      height: '100%',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#E5E7EB',
    },
    lineupPlayerAvatarFallbackText: {
      color: '#4B5563',
      fontSize: 16,
      fontWeight: '900',
    },
    lineupRatingChip: {
      position: 'absolute',
      right: -8,
      top: -8,
      borderRadius: 999,
      minWidth: 40,
      paddingHorizontal: 6,
      paddingVertical: 2,
      alignItems: 'center',
      zIndex: 10,
      borderWidth: 1.5,
      borderColor: colors.surfaceElevated,
    },
    lineupRatingChipGood: {
      backgroundColor: '#34D399',
    },
    lineupRatingChipWarning: {
      backgroundColor: '#FB923C',
    },
    lineupRatingChipElite: {
      backgroundColor: '#38BDF8',
    },
    lineupRatingChipNeutral: {
      backgroundColor: '#A3A3A3',
    },
    lineupRatingChipText: {
      color: '#111827',
      fontSize: 12,
      fontWeight: '900',
    },
    lineupTeamRatingChip: {
      position: 'relative',
      right: 0,
      top: 0,
      minWidth: 32,
    },
    lineupPlayerEventWrap: {
      position: 'absolute',
      left: -6,
      top: -4,
      alignItems: 'center',
      gap: 1,
      zIndex: 10,
    },
    lineupPlayerEventMinute: {
      color: '#E5E7EB',
      fontSize: 11,
      fontWeight: '800',
    },
    lineupBenchEventWrap: {
      position: 'absolute',
      left: -4,
      top: -4,
      alignItems: 'center',
      gap: 1,
    },
    lineupBenchEventMinute: {
      color: '#34D399',
      fontSize: 11,
      fontWeight: '800',
    },
    lineupPlayerGoalIconWrap: {
      position: 'absolute',
      right: -2,
      bottom: -2,
      width: 19,
      height: 19,
      borderRadius: 999,
      backgroundColor: '#E5E7EB',
      alignItems: 'center',
      justifyContent: 'center',
    },
    lineupPlayerCardIconWrap: {
      position: 'absolute',
      left: -2,
      bottom: -2,
      width: 19,
      height: 19,
      borderRadius: 999,
      backgroundColor: '#E5E7EB',
      alignItems: 'center',
      justifyContent: 'center',
    },
    lineupCaptainArmbandWrap: {
      position: 'absolute',
      left: -4,
      top: -4,
      backgroundColor: '#111827',
      borderRadius: 4,
      zIndex: 10,
    },
    lineupPlayerName: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '700',
      textAlign: 'center',
      marginTop: 2,
    },
    lineupTwoColumnsWrap: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
    },
    lineupColumn: {
      flex: 1,
      gap: 8,
    },
    lineupColumnHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    lineupColumnTeamLogo: {
      width: 18,
      height: 18,
    },
    lineupColumnTeamName: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '800',
    },
    lineupColumnList: {
      gap: 10,
    },
    lineupCoachCard: {
      alignItems: 'center',
      gap: 8,
      paddingVertical: 4,
    },
    lineupCoachAvatarWrap: {
      width: 54,
      height: 54,
      position: 'relative',
    },
    lineupCoachAvatar: {
      width: '100%',
      height: '100%',
    },
    lineupCoachAvatarFallback: {
      width: '100%',
      height: '100%',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#E5E7EB',
    },
    lineupCoachName: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '700',
      textAlign: 'center',
    },
    lineupBenchItem: {
      alignItems: 'center',
      gap: 4,
      paddingBottom: 2,
    },
    lineupBenchPosition: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
    },
    // The Absences styles are completely removed as requested
    lineupLegendGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      rowGap: 12,
      columnGap: 8,
    },
    lineupLegendItem: {
      width: '48%',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    lineupLegendText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '600',
      flex: 1,
    },
  });
}

export type MatchDetailsTabStyles = ReturnType<typeof createMatchDetailsTabStyles>;
