import { StyleSheet } from 'react-native';

import type { ThemeColors } from '@ui/shared/theme/theme';

export function createPlayerProfileTabStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    content: {
      paddingHorizontal: 16,
      paddingTop: 20,
      paddingBottom: 28,
      gap: 16,
    },
    card: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      paddingHorizontal: 14,
      paddingVertical: 14,
    },
    cardTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 10,
    },
    cardTitle: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '700',
      flexShrink: 1,
    },
    cardSubtitle: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '500',
      lineHeight: 18,
      marginTop: -4,
      marginBottom: 10,
    },
    infoGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    infoTile: {
      flexGrow: 1,
      flexBasis: '31%',
      minWidth: 90,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceElevated,
      paddingHorizontal: 8,
      paddingVertical: 10,
      gap: 4,
    },
    infoTileHead: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    infoTileFlag: {
      width: 16,
      height: 12,
      borderRadius: 2,
      borderWidth: 1,
      borderColor: colors.border,
    },
    infoTileLabel: {
      color: colors.textMuted,
      fontSize: 10,
      fontWeight: '600',
      textTransform: 'uppercase',
      flexShrink: 1,
    },
    infoTileValue: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '700',
    },
    competitionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 12,
    },
    competitionLogoWrap: {
      width: 30,
      height: 30,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceElevated,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    competitionLogo: {
      width: 20,
      height: 20,
    },
    competitionMeta: {
      flex: 1,
      minWidth: 0,
    },
    competitionName: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '700',
    },
    competitionSeason: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '500',
      marginTop: 2,
    },
    competitionKpis: {
      flexDirection: 'row',
      gap: 8,
    },
    competitionKpi: {
      flex: 1,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceElevated,
      paddingHorizontal: 8,
      paddingVertical: 8,
      alignItems: 'center',
      gap: 4,
    },
    competitionKpiLabelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    competitionKpiLabel: {
      color: colors.textMuted,
      fontSize: 9,
      fontWeight: '600',
      textTransform: 'uppercase',
    },
    competitionKpiValue: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '800',
    },
    ratingBadge: {
      minWidth: 44,
      borderRadius: 10,
      paddingHorizontal: 4,
      paddingVertical: 4,
      alignItems: 'center',
      justifyContent: 'center',
    },
    ratingBadgeText: {
      fontSize: 15,
      fontWeight: '800',
    },
    helperText: {
      color: colors.textMuted,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '500',
    },
    positionContent: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
    },
    positionTextColumn: {
      flex: 1,
      minWidth: 140,
      gap: 10,
    },
    positionLabel: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '600',
      textTransform: 'uppercase',
    },
    positionValue: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '700',
      lineHeight: 22,
    },
    secondaryPositionValue: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '600',
      lineHeight: 20,
    },
    pitchWrap: {
      flexGrow: 1,
      minWidth: 180,
      alignItems: 'center',
    },
    pitch: {
      width: '100%',
      maxWidth: 220,
      height: 250,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceElevated,
      overflow: 'hidden',
    },
    pitchHalfLine: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: '50%',
      height: 1,
      backgroundColor: colors.border,
    },
    pitchCenterCircle: {
      position: 'absolute',
      left: '50%',
      top: '50%',
      width: 46,
      height: 46,
      borderRadius: 23,
      borderWidth: 1,
      borderColor: colors.border,
      transform: [{ translateX: -23 }, { translateY: -23 }],
    },
    pitchBoxTop: {
      position: 'absolute',
      left: '22%',
      right: '22%',
      top: 0,
      height: 36,
      borderWidth: 1,
      borderColor: colors.border,
      borderTopWidth: 0,
    },
    pitchBoxBottom: {
      position: 'absolute',
      left: '22%',
      right: '22%',
      bottom: 0,
      height: 36,
      borderWidth: 1,
      borderColor: colors.border,
      borderBottomWidth: 0,
    },
    pitchBadge: {
      position: 'absolute',
      minWidth: 32,
      borderRadius: 10,
      borderWidth: 1,
      paddingHorizontal: 6,
      paddingVertical: 2,
      alignItems: 'center',
      justifyContent: 'center',
      transform: [{ translateX: -16 }, { translateY: -10 }],
    },
    pitchBadgeText: {
      fontSize: 12,
      fontWeight: '700',
    },
    trophiesWrap: {
      gap: 10,
    },
    clubCard: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceElevated,
      overflow: 'hidden',
    },
    clubHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 12,
      paddingVertical: 11,
      backgroundColor: colors.surface,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    clubLogoWrap: {
      width: 34,
      height: 34,
      borderRadius: 17,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceElevated,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    clubLogo: {
      width: 24,
      height: 24,
    },
    clubName: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '700',
      flex: 1,
    },
    trophyCompetitionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    trophyCount: {
      width: 20,
      color: colors.textMuted,
      fontSize: 15,
      fontWeight: '600',
      textAlign: 'right',
    },
    trophyBody: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    trophyTitleLine: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      flexWrap: 'wrap',
    },
    trophyName: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '600',
      flexShrink: 1,
    },
    trophySeasons: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '500',
      lineHeight: 18,
    },
    trophyDivider: {
      height: 1,
      backgroundColor: colors.border,
      marginLeft: 12,
      marginRight: 12,
    },
  });
}

export type PlayerProfileTabStyles = ReturnType<typeof createPlayerProfileTabStyles>;
