services:
  footalert-site-vitrine:
    container_name: footalert-site-vitrine
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:8080"
