declare module 'react-native-config' {
  export interface NativeConfig {
    APP_ENV?: string;
    MOBILE_API_BASE_URL?: string;
    WEB_API_BASE_URL?: string;
    DESKTOP_API_BASE_URL?: string;
    WEB_APP_ORIGIN?: string;
    MOBILE_VALIDATION_MODE?: string;
    MOBILE_PRIVACY_POLICY_URL?: string;
    MOBILE_TERMS_OF_USE_URL?: string;
    MOBILE_SUPPORT_URL?: string;
    MOBILE_FOLLOW_US_URL?: string;
    MOBILE_APP_STORE_URL?: string;
    MOBILE_PLAY_STORE_URL?: string;
    MOBILE_PUSH_TOKEN?: string;
    MOBILE_AUTH_ATTESTATION_MODE?: string;
    MOBILE_ATTESTATION_STRATEGY?: string;
    MOBILE_SESSION_TOKEN_TTL_MS?: string;
    MOBILE_PINNING_ENABLED?: string;
    MOBILE_PINNING_HOST?: string;
    MOBILE_PINNING_SPKI_PRIMARY?: string;
    MOBILE_PINNING_SPKI_BACKUP?: string;
    MOBILE_PINNING_KILL_SWITCH_ALLOW?: string;
    ASSET_CDN_REWRITE_ENABLED?: string;
    ASSET_CDN_BASE_URL?: string;
    MATCHES_QUERY_STALE_TIME_MS?: string;
    MATCHES_LIVE_REFRESH_INTERVAL_MS?: string;
    MATCHES_SLOW_REFRESH_INTERVAL_MS?: string;
    MATCHES_MAX_REFRESH_BACKOFF_MS?: string;
    MATCHES_BATTERY_SAVER_REFRESH_INTERVAL_MS?: string;
    FOLLOWS_SEARCH_DEBOUNCE_MS?: string;
    FOLLOWS_SEARCH_MIN_CHARS?: string;
    FOLLOWS_SEARCH_RESULTS_LIMIT?: string;
    FOLLOWS_TEAM_NEXT_FIXTURE_TTL_MS?: string;
    FOLLOWS_PLAYER_STATS_TTL_MS?: string;
    FOLLOWS_TRENDS_TTL_MS?: string;
    FOLLOWS_TRENDS_LEAGUE_COUNT?: string;
    FOLLOWS_TRENDS_TEAMS_LIMIT?: string;
    FOLLOWS_TRENDS_PLAYERS_LIMIT?: string;
    FOLLOWS_MAX_FOLLOWED_TEAMS?: string;
    FOLLOWS_MAX_FOLLOWED_PLAYERS?: string;
    FOLLOWS_MAX_FOLLOWED_LEAGUES?: string;
    MOBILE_ENABLE_BFF_PLAYER_AGGREGATES?: string;
    MOBILE_ENABLE_PLAYER_OVERVIEW_AGGREGATE?: string;
    MOBILE_ENABLE_PLAYER_STATS_CATALOG_AGGREGATE?: string;
    MOBILE_ENABLE_BFF_TEAM_FULL?: string;
    MOBILE_ENABLE_BFF_PLAYER_FULL?: string;
    MOBILE_ENABLE_BFF_COMPETITION_FULL?: string;
    MOBILE_ENABLE_BFF_MATCH_FULL?: string;
    MOBILE_ENABLE_SQLITE_LOCAL_FIRST?: string;
    MOBILE_QUERY_PERSIST_MAX_BYTES?: string;
    NOTIFICATIONS_MATCH_BACKEND_ENABLED?: string;
    MOBILE_ENABLE_STORYBOOK?: string;
  }

  const Config: NativeConfig;
  export default Config;
}
