import { StyleSheet } from 'react-native';

import type { ThemeColors } from '@ui/shared/theme/theme';

export function createTeamOverviewStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
    },
    content: {
      gap: 14,
      paddingHorizontal: 16,
      paddingBottom: 30,
    },
    stateCard: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      padding: 14,
      gap: 8,
    },
    loadingIndicator: {
      alignSelf: 'center',
    },
    stateText: {
      color: colors.textMuted,
      fontSize: 15,
      fontWeight: '600',
    },
    retryText: {
      color: colors.primary,
      fontSize: 15,
      fontWeight: '700',
    },
    card: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      padding: 14,
      gap: 12,
    },
    cardTitle: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '800',
    },
    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
      minWidth: 0,
    },
    sectionSubtitle: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '700',
      flexShrink: 1,
      textAlign: 'right',
    },
    nextMetaRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 8,
      flexWrap: 'wrap',
    },
    nextMeta: {
      color: colors.textMuted,
      fontSize: 14,
      fontWeight: '600',
      flexShrink: 1,
    },
    leaguePill: {
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 4,
      backgroundColor: colors.surfaceElevated,
      borderWidth: 1,
      borderColor: colors.border,
      maxWidth: '70%',
    },
    leaguePillText: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '700',
    },
    nextMatchRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    teamSide: {
      flex: 1,
      alignItems: 'center',
      gap: 6,
    },
    teamBadge: {
      width: 32,
      height: 32,
      borderRadius: 16,
      overflow: 'hidden',
      backgroundColor: colors.surfaceElevated,
      alignItems: 'center',
      justifyContent: 'center',
    },
    teamBadgeImage: {
      width: 26,
      height: 26,
    },
    teamName: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '700',
      textAlign: 'center',
    },
    kickoffWrap: {
      alignItems: 'center',
      gap: 4,
      minWidth: 70,
    },
    kickoff: {
      color: colors.text,
      fontSize: 24,
      fontWeight: '900',
      letterSpacing: -1,
      textAlign: 'center',
    },
    kickoffLabel: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
    },
    formRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 8,
    },
    formItem: {
      flex: 1,
      alignItems: 'center',
      gap: 8,
      minWidth: 52,
    },
    formBadge: {
      minWidth: 48,
      borderRadius: 11,
      paddingVertical: 6,
      paddingHorizontal: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surfaceElevated,
      borderWidth: 1,
      borderColor: colors.border,
    },
    formBadgeWin: {
      backgroundColor: 'rgba(21,248,106,0.22)',
    },
    formBadgeDraw: {
      backgroundColor: 'rgba(245,158,11,0.25)',
    },
    formBadgeLoss: {
      backgroundColor: 'rgba(248,113,113,0.28)',
    },
    formBadgeText: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '800',
    },
    formLogo: {
      width: 22,
      height: 22,
    },
    formLogoWrap: {
      width: 32,
      height: 32,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceElevated,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    formLogoFallback: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '800',
    },
    statsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    statCell: {
      width: '48%',
      borderRadius: 12,
      paddingVertical: 10,
      paddingHorizontal: 10,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceElevated,
      gap: 3,
    },
    statLabelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    statLabel: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '700',
      flexShrink: 1,
    },
    statIcon: {
      width: 14,
      textAlign: 'center',
    },
    statValue: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '900',
    },
    statValuePositive: {
      color: '#22F08A',
    },
    statValueNegative: {
      color: '#F87171',
    },
    statValueNeutral: {
      color: colors.text,
    },
    pitch: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: '#2A2D2B',
      paddingHorizontal: 10,
      paddingVertical: 12,
      gap: 12,
    },
    pitchHalfLine: {
      height: 1,
      backgroundColor: 'rgba(255,255,255,0.12)',
    },
    lineupRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 6,
      minHeight: 66,
    },
    lineupPlayer: {
      flex: 1,
      alignItems: 'center',
      gap: 4,
    },
    lineupAvatarBlock: {
      width: 44,
      height: 44,
      justifyContent: 'center',
      alignItems: 'center',
      position: 'relative',
    },
    lineupAvatarWrap: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'rgba(255,255,255,0.08)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    lineupAvatar: {
      width: 40,
      height: 40,
    },
    lineupRating: {
      position: 'absolute',
      top: -5,
      right: -4,
      borderRadius: 9,
      backgroundColor: colors.primary,
      minWidth: 24,
      paddingHorizontal: 5,
      paddingVertical: 1,
      borderWidth: 1,
      borderColor: '#0B0B0B',
      alignItems: 'center',
    },
    lineupRatingText: {
      color: '#000',
      fontSize: 10,
      fontWeight: '900',
    },
    lineupName: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '700',
      textAlign: 'center',
      lineHeight: 15,
      minHeight: 30,
    },
    tableHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingBottom: 6,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      gap: 4,
    },
    tableRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      gap: 4,
    },
    tableRowTarget: {
      backgroundColor: colors.surfaceElevated,
      borderRadius: 8,
      paddingHorizontal: 4,
    },
    colRank: {
      width: 26,
      alignItems: 'center',
    },
    colTeam: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      minWidth: 0,
    },
    colSmall: {
      width: 24,
      alignItems: 'center',
    },
    colDiff: {
      width: 38,
      alignItems: 'center',
    },
    colPoints: {
      width: 34,
      alignItems: 'center',
    },
    tableHeaderText: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '700',
    },
    tableCellText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '700',
    },
    tableCellTextBold: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '900',
    },
    miniStandingTitle: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '800',
      flexShrink: 1,
    },
    miniStandingHeaderRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      minWidth: 0,
    },
    miniStandingLeagueLogo: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: colors.surfaceElevated,
    },
    teamLogo: {
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: colors.surfaceElevated,
    },
    teamRowName: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '700',
      flexShrink: 1,
    },
    historyHeaderRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      minWidth: 0,
      maxWidth: '48%',
      flexShrink: 1,
      justifyContent: 'flex-end',
    },
    historyLeagueBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: 'rgba(34,240,138,0.35)',
      backgroundColor: 'rgba(34,240,138,0.12)',
      paddingHorizontal: 8,
      paddingVertical: 4,
      maxWidth: '100%',
      minWidth: 0,
    },
    historyLeagueLogo: {
      width: 16,
      height: 16,
      borderRadius: 8,
      backgroundColor: colors.surfaceElevated,
    },
    historyLeagueName: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '800',
      flexShrink: 1,
      minWidth: 0,
    },
    historyTitle: {
      flex: 1,
      minWidth: 0,
      marginRight: 6,
    },
    historyChart: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: '#121E1A',
      padding: 10,
      gap: 10,
    },
    historyGraphCanvas: {
      height: 90,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: 'rgba(7,20,16,0.85)',
      overflow: 'hidden',
    },
    historyColumns: {
      ...StyleSheet.absoluteFillObject,
      flexDirection: 'row',
    },
    historyColumn: {
      flex: 1,
      borderRightWidth: 1,
      borderRightColor: 'rgba(255,255,255,0.08)',
    },
    historyColumnAlt: {
      backgroundColor: 'rgba(255,255,255,0.03)',
    },
    historyColumnCurrent: {
      backgroundColor: 'rgba(34,240,138,0.16)',
    },
    historyColumnLast: {
      borderRightWidth: 0,
    },
    historyConnectionHorizontal: {
      position: 'absolute',
      height: 2.5,
      backgroundColor: 'rgba(114,234,193,0.8)',
      borderRadius: 999,
    },
    historyConnectionVertical: {
      position: 'absolute',
      width: 2.5,
      backgroundColor: 'rgba(114,234,193,0.45)',
      borderRadius: 999,
    },
    historyItem: {
      position: 'absolute',
      width: 36,
      height: 36,
      borderRadius: 18,
      borderWidth: 2,
      alignItems: 'center',
      justifyContent: 'center',
    },
    historyItemText: {
      fontSize: 15,
      fontWeight: '800',
    },
    historySeasonRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 8,
    },
    historySeasonItem: {
      flex: 1,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(255,255,255,0.02)',
      paddingVertical: 5,
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: 0,
    },
    historySeasonItemActive: {
      borderColor: 'rgba(34,240,138,0.55)',
      backgroundColor: 'rgba(34,240,138,0.22)',
    },
    historySeasonText: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '700',
      textAlign: 'center',
    },
    historySeasonTextActive: {
      color: colors.text,
      fontWeight: '900',
    },
    coachHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    coachAvatarWrap: {
      width: 44,
      height: 44,
      borderRadius: 22,
      overflow: 'hidden',
      backgroundColor: colors.surfaceElevated,
      alignItems: 'center',
      justifyContent: 'center',
    },
    coachAvatar: {
      width: 44,
      height: 44,
    },
    coachName: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '800',
      flexShrink: 1,
    },
    coachInfoWrap: {
      flex: 1,
      minWidth: 0,
    },
    coachMeta: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '600',
    },
    coachStatsRow: {
      flexDirection: 'row',
      gap: 10,
    },
    coachStat: {
      flex: 1,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceElevated,
      paddingHorizontal: 10,
      paddingVertical: 8,
      gap: 2,
    },
    coachStatLabel: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '700',
    },
    coachStatValue: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '900',
    },
    coachRecord: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '700',
    },
    leadersGrid: {
      flexDirection: 'row',
      gap: 10,
      flexWrap: 'wrap',
    },
    leaderCard: {
      width: '48%',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceElevated,
      padding: 10,
      gap: 8,
      minHeight: 140,
    },
    leaderTitle: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '800',
    },
    leaderMainName: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '900',
      lineHeight: 20,
    },
    leaderMainRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    leaderMainAvatarWrap: {
      width: 42,
      height: 42,
      borderRadius: 21,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    leaderMainAvatar: {
      width: 42,
      height: 42,
    },
    leaderMainTextWrap: {
      flex: 1,
      minWidth: 0,
    },
    leaderMainValue: {
      color: colors.primary,
      fontSize: 24,
      fontWeight: '900',
    },
    leaderItemLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      flex: 1,
      minWidth: 0,
    },
    leaderItemAvatarWrap: {
      width: 24,
      height: 24,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    leaderItemAvatar: {
      width: 24,
      height: 24,
    },
    leaderAvatarFallback: {
      color: colors.textMuted,
      fontSize: 10,
      fontWeight: '800',
    },
    leaderItemRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 8,
    },
    leaderItemName: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '600',
      flexShrink: 1,
    },
    leaderItemValue: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '800',
    },
    competitionsList: {
      gap: 10,
    },
    competitionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceElevated,
      paddingHorizontal: 10,
      paddingVertical: 9,
    },
    competitionLogo: {
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: colors.surface,
    },
    competitionTextWrap: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    competitionName: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '800',
    },
    competitionSeason: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '700',
    },
    splitRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 10,
    },
    splitLabel: {
      color: colors.textMuted,
      fontSize: 14,
      fontWeight: '700',
      flexShrink: 1,
    },
    splitValue: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '800',
      textAlign: 'right',
      flexShrink: 1,
    },
    stadiumName: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '900',
    },
    stadiumMeta: {
      color: colors.textMuted,
      fontSize: 14,
      fontWeight: '600',
    },
    stadiumHero: {
      minHeight: 126,
      borderRadius: 14,
      overflow: 'hidden',
      backgroundColor: colors.surfaceElevated,
      borderWidth: 1,
      borderColor: colors.border,
    },
    stadiumHeroImage: {
      ...StyleSheet.absoluteFillObject,
      width: '100%',
      height: '100%',
    },
    stadiumHeroOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0,0,0,0.42)',
    },
    stadiumHeroContent: {
      paddingHorizontal: 12,
      paddingVertical: 12,
      justifyContent: 'flex-end',
      flex: 1,
      gap: 4,
    },
    stadiumHeroName: {
      color: '#FFFFFF',
      fontSize: 20,
      fontWeight: '900',
      textShadowColor: 'rgba(0,0,0,0.4)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
    stadiumHeroMeta: {
      color: 'rgba(255,255,255,0.88)',
      fontSize: 14,
      fontWeight: '700',
      textShadowColor: 'rgba(0,0,0,0.4)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
  });
}

export type TeamOverviewStyles = ReturnType<typeof createTeamOverviewStyles>;
