import { StyleSheet } from 'react-native';

import type { ThemeColors } from '@ui/shared/theme/theme';

export function createTeamStatsTabStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
    },
    content: {
      paddingHorizontal: 16,
      paddingBottom: 24,
      gap: 10,
    },
    stateCard: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      paddingHorizontal: 14,
      paddingVertical: 12,
      gap: 8,
      marginTop: 12,
    },
    loadingIndicator: {
      alignSelf: 'center',
    },
    stateText: {
      color: colors.textMuted,
      fontSize: 14,
      fontWeight: '500',
    },
    retryText: {
      color: colors.primary,
      fontSize: 14,
      fontWeight: '600',
    },
    sectionTitle: {
      color: colors.text,
      fontSize: 22,
      lineHeight: 26,
      fontWeight: '800',
      marginTop: 8,
    },
    card: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      padding: 12,
      gap: 10,
    },
    cardTitleRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 12,
    },
    cardTitle: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '700',
      flex: 1,
      lineHeight: 20,
    },
    cardValue: {
      color: colors.text,
      fontSize: 30,
      lineHeight: 32,
      fontWeight: '800',
      flexShrink: 1,
      textAlign: 'right',
    },
    pointsValue: {
      color: colors.text,
      fontSize: 27,
      lineHeight: 30,
      fontWeight: '700',
      fontVariant: ['tabular-nums'],
      letterSpacing: 0.2,
      minWidth: 54,
      textAlign: 'right',
    },
    goalsValue: {
      color: colors.text,
      fontSize: 24,
      lineHeight: 28,
      fontWeight: '700',
      fontVariant: ['tabular-nums'],
      letterSpacing: 0.3,
      minWidth: 78,
      textAlign: 'right',
    },
    mutedValue: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '600',
    },
    divider: {
      height: 1,
      backgroundColor: colors.border,
    },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    rowLabel: {
      color: colors.textMuted,
      fontSize: 14,
      fontWeight: '600',
      flex: 1,
    },
    rowValue: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '700',
    },
    tableHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingVertical: 2,
    },
    tableHeadLabel: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '700',
      width: 22,
      textAlign: 'center',
    },
    venueLabel: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '600',
      width: 60,
    },
    tableValue: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '600',
      width: 22,
      textAlign: 'center',
    },
    scoreColumn: {
      width: 40,
    },
    diffColumn: {
      width: 26,
    },
    barsWrap: {
      gap: 10,
    },
    barRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    barLabel: {
      width: 72,
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '700',
    },
    barTrack: {
      flex: 1,
      height: 10,
      borderRadius: 999,
      overflow: 'hidden',
      backgroundColor: colors.surfaceElevated,
    },
    barFill: {
      height: 10,
      borderRadius: 999,
      backgroundColor: colors.primary,
    },
    barValue: {
      width: 28,
      textAlign: 'right',
      color: colors.text,
      fontSize: 13,
      fontWeight: '700',
    },
    playersGrid: {
      gap: 10,
    },
    playersCard: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      padding: 12,
      gap: 8,
    },
    playersCardTitle: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '700',
    },
    playerRow: {
      minHeight: 44,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    playerLeft: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    playerPhotoContainer: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: colors.surfaceElevated,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    playerPhoto: {
      width: 30,
      height: 30,
      borderRadius: 15,
    },
    playerInfo: {
      flex: 1,
      minWidth: 0,
      gap: 1,
    },
    playerName: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '600',
    },
    playerMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    playerMeta: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '500',
      flex: 1,
      minWidth: 0,
    },
    playerTeamLogoContainer: {
      width: 16,
      height: 16,
      borderRadius: 8,
      backgroundColor: colors.surfaceElevated,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    playerTeamLogo: {
      width: 12,
      height: 12,
    },
    playerValue: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '700',
      minWidth: 48,
      textAlign: 'right',
    },
    comparisonCard: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      padding: 12,
      gap: 8,
    },
    comparisonTopRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 12,
    },
    comparisonTitle: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '700',
      flex: 1,
      lineHeight: 18,
    },
    comparisonValue: {
      color: colors.primary,
      fontSize: 20,
      fontWeight: '800',
    },
    comparisonRank: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '600',
    },
    leaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 6,
    },
    leaderLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      flex: 1,
      minWidth: 0,
    },
    leaderRank: {
      color: colors.textMuted,
      width: 14,
      fontSize: 11,
      fontWeight: '600',
      textAlign: 'right',
    },
    leaderLogoContainer: {
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: colors.surfaceElevated,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    leaderLogo: {
      width: 14,
      height: 14,
    },
    leaderName: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '500',
      flex: 1,
    },
    leaderValue: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '600',
      minWidth: 44,
      textAlign: 'right',
    },
  });
}

export type TeamStatsTabStyles = ReturnType<typeof createTeamStatsTabStyles>;
